#pragma once

//#define PACKET_STX "Q\1"

//#define MAKE_STX(a)			(memcpy(a, PACKET_STX,  2))
#define HEADER_SIZE			8		//2+2+2+2


//General status
#define P_SUCCESS			0
#define P_SOCKET_ERROR		-1
#define P_FAILED			1


//enum MAIN_PROTOCAL
//{
//	PT_DATABASE			= 1,
//	PT_SERVER_MSG		= 2,
//	PT_AUTHENTICATION	= 3,
//	PT_ECHO				= 4,
//	PT_MESSENGER		= 5,
//	PT_FILE				= 6,
//	PT_STATISTIC		= 7,
//	PT_CHECK_CONN		= 8,
//	PT_UPDATE			= 9,
//	PT_MANAGEMENT		= 10,
//	PT_APP_CLIENT		= 11,
//	PT_USER_APP_CLIENT	= 12,
//	PT_HELP_APP_CLIENT  = 13,
//};
//
//enum SUB_PROTOCOLL_COMMON
//{ 
//	PST_SUCCESS				= 1,
//	PST_FAIL				= 2,
//	PST_OK					= 3,
//	PST_CANCEL				= 4,
//	PST_ERROR				= 5,
//	PST_SERVER_TO_SERVER	= 6,
//	PST_ECHO				= 7
//};
//
//enum SUB_PROTOCOL_DATABASE
//{
//	PST_EXECUTE_TRAN	= 10,
//	PST_CANCEL_TRAN		= 11,
//	PST_TRAN_OPTION		= 12,
//	PST_EXECUTE_TRAN2	= 13,
//};
//
//enum SUB_PROTOCOL_AUTHENTICATION
//{
//	PST_SEND_CYPHER_TEXT					= 10,
//	PST_SEND_CYPHER_TEXT_USER_APP			= 11,
//	PST_IP_AUTHENTICATION					= 12,
//	PST_SEND_CYPHER_TEXT_USER_APP_NO_CERT	= 13,
//};
//
//enum SUB_PROTOCOL_MESSENGER
//{
//	PST_LOGIN					= 10,
//	PST_MAKE_ROOM				= 11,
//	PST_GET_ROOM_MEMBER			= 12,
//	PST_SEND_MSG				= 13,
//	PST_MEMBER_LIST				= 14,
//	PST_ADD_CHAT_MEMBER			= 15,
//	PST_GO_OUT_OF_ROOM			= 16,
//	PST_LOSE_CONTROL			= 17,
//	PST_CHANGE_STATUS			= 18,
//	PST_SEND_WRITING			= 19,
//	PST_SEND_MSG_FAILED			= 20,
//	PST_CHANGE_COLOR			= 21,
//	PST_SETUP_INFO				= 22,
//	PST_NOTIFY_LOGIN			= 23,
//	PST_SERVER_CONFIG			= 24,
//	PST_REDIRECT_FILE			= 25,
//	PST_SEND_NOTE				= 26,
//	PST_USER_POWER				= 27,
//	PST_ENTER_SIMPLE_ROOM		= 28,
//	PST_GO_OUT_OF_SIMPLE_ROOM	= 29,
//	PST_SEND_MSG_SIMPLE_ROOM	= 30,
//	PST_SEND_DIRECT_DATA		= 31,
//	PST_SET_KEYPHONE_ID			= 32,
//	PST_SEND_DIRECT_NO_HEADER	= 33,
//	PST_CHANGE_TRAN_ROOM		= 34,
//	PST_SET_PROXY_TELSERVER		= 35,
//	PST_SIMPLE_ROOM_INOUT		= 36,
//	PST_ALLOC_ORDER_INFO		= 37,
//	PST_SEND_PROGRAM_LOG		= 38,
//	
//	//여기서 부터 사용자정의 메시지 입니다.
//	PSTU_MESSAGE				= 100,
//	PSTU_SEARCH_ROUTE			= 101,
//	PSTU_CARD_PAYMENT			= 102,
//	PSTU_CARD_CANCEL			= 103,
//	PSTU_ISSUE_CASH_RECEIPT		= 104,
//	PSTU_RESEND_MAIL			= 105,
//	PSTU_CANCEL_CASH_RECEIPT	= 106,
//	PSTU_CARD_PAYMENT2			= 107,
//	PSTU_CARD_PROTOCOL_END		= 120,
//	PSTU_SEARCH_ROUTE2			= 121,
//}; 
//
//enum SUB_PROTOCOL_FILE 
//{
//	PST_FILE_TRAN				= 10,
//	PST_FILE_DATA				= 11,
//	PST_REDIRECT_TRAN			= 12,
//	PST_REDIRECT_DATA			= 13,
//	PST_REQUEST_FILE			= 14, 
//	PST_CANCEL_FILE				= 15,
//	PST_CANCEL_REDIRECT			= 16,
//	PST_TRAN_TARGET_KBPS		= 17,
//	PST_TRAN_MAX_KBPS			= 18, 
//	PST_ACCEPT_FILE				= 19,
//	PST_TEST_REDIRECT			= 20,
//	PST_FILE_TRAN_END			= 21,
//	PST_REQUEST_FILE_NO_HANDLE	= 22
//};
//
//enum SUB_PROTOCOL_STAT
//{
//	PST_STAT_INFO				= 10
//};
//
//enum SUB_PROTOCOL_UPDATE
//{
//	PST_CHECK_UPDATE_EXE		= 10,
//	PST_UPDATE_FILE_LIST		= 11,
//	PST_UPDATE_INI_LIST			= 12,
//	PST_COPY_FILE				= 13,
//	PST_MAKE_UPDATE_LIST		= 14,
//	PST_COPY_FILE_WILDCARD		= 15
//};
//
//enum SUB_PROTOCOL_MANAGEMENT	
//{
//	PST_SERVER_SIGN_ON			= 10,
//	PST_SERVICE_START			= 11,
//	PST_SERVICE_STOP			= 12,
//	PST_SERVICE_RESTART			= 13,
//	PST_SERVICE_LIST			= 14,
//	PST_SERVICE_COPY_FILE		= 15,
//	PST_TS_DISCON				= 16,
//	PST_FILE_LIST_IN_DIR		= 17, 
//	PST_DRIVE_FREE_SPACE		= 18,
//	PST_SELF_UPDATE				= 19,
//	PST_DELETE_FILE				= 20,
//	PST_BATCH_COMMAND			= 21,
//	PST_UPDATE_SERVER			= 22
//};
//
//
//enum SUB_PROTOCOL_APP_CLIENT
//{
//	PST_APP_LOGIN				= 10,
//	PST_CLIENT_INFO				= 11,
//	PST_ORDER					= 12,
//	PST_ALLOCATE_ORDER			= 13,
//	PST_CANCEL_ORDER			= 14,
//	PST_APP_GPS_POS				= 15,
//	PST_NEAR_RIDER				= 16,
//	PST_NEAR_POI				= 17,
//	PST_DB_EXECUTE				= 18,
//	PST_NOTICE					= 19,
//	PST_BALANCE_WARNNING		= 20,
//	PST_MESSAGE					= 21,
//	PST_HAVE_ORDERS				= 22,
//	PST_FINISH_ORDER			= 23,
//	PST_SEND_RIDER_PICTURE		= 24,	//사용안함
//	PST_RECV_RIDER_PHOTO		= 25,	//PST_RECV_RIDER_PICTURE
//	PST_DOWNLOAD_RIDER_PHOTO	= 25,
//	PST_PRE_ALLOCATE_ORDER		= 26,
//	PST_PRE_ALLOCATE_WARNNING	= 27,
//	PST_CHAT_MESSAGE			= 28,
//	PST_RIDER_OPTION			= 29,
//	PST_SEND_ORDER_SIGN			= 30,
//	PST_UPLOAD_ORDER_SIGN		= 30,
//	PST_RECV_ORDER_SIGN			= 31,
//	PST_DOWNLOAD_ORDER_SIGN		= 31,
//	PST_SERVER_NOTICE			= 32,
//	PST_NO_USE					= 33,
//	PST_REFUSE_ORDER			= 34,
//	PST_RUNNING_PROCESS_LIST	= 35, 
//	PST_APP_LOGOUT				= 36,	//서버간 통신용으로만 사용
//	PST_UPDATE_ALL_RIDER_PHOTO_FILES = 37,
//	PST_ORDER_LIST				= 38
//};
//
//
////AppServer의 서버의 쿼리 결과를 다른 AppServer로 넘겨줄 때 사용하는 프로토콜
////SS는 Server To Server 약자
//enum SUB_PROTOCOL_APP_SERVER
//{
//	PST_FROM_APP_SERVER			= 200,
//	PST_SS_SEND_RIDER_INFO		= 201,
//	PST_SS_CHANGE_ASSIGN_SERVER	= 202,
//	PST_SS_SEND_ALL_RIDER_INFO  = 203,
//	PST_SS_ORDER_LIST			= 204,
//	PST_SS_ASSIGN_ORDER			= 205,
//	PST_SS_SEND_MY_INFO			= 206,
//	PST_SS_REFUSAL_RIDER		= 207,
//	PST_SS_RIDER_STATE			= 208,
//	PST_SS_RIDER_HAVE_ORDERS	= 209,
//	PST_SS_FINISH_ORDER			= 210,
//	PST_SS_ORDER_ASSIGN_STATE	= 211,
//	PST_SS_INTER_FPROCESS_DATA	= 212
//};
//
//
//enum SUB_PROTOCOL_USER_APP_CLIENT
//{
//	PST_USER_APP_LOGIN					= 10,
//	PST_CHANGE_CNO						= 11,
//	PST_SHUTTLE_INFO					= 12,
//	PST_SET_OPTION						= 13,	//PST_SET_VIEW_RANGE
//	PST_UNUSE							= 14,
//	PST_APP_GPS_POS2					= PST_APP_GPS_POS,
//	PST_GET_MIC_CONTROL					= 16,
//	PST_RELEASE_MIC_CONTROL				= 17,
//	PST_DB_EXECUTE_TRAN2						= PST_DB_EXECUTE,	//18
//	PST_MIC_CONTROL_INFO				= 19,
//	PST_VERIFY_SHUTTLE_RFID				= 20,
//	PST_CHANGE_COMPANY_CODE				= 21,
//	PST_SHUTTLE_NEAR_CALL_COUNT			= 22,
//	PST_SEND_SHUTTLE_LOG				= 23,
//	PST_SEND_SMS_AUTH_FOR_LOGIN			= 24,
//	PST_UPDATE_DEVICE_AUTH				= 25,
//	PST_BOARDING_SHUTTLE				= 26,
//	PST_VOICE_DATA						= 27,
//	PST_CHANGE_ADMIN_LOGIN_CODE			= 28,
//	PST_POINT_LOCATION_INFO				= 29,
//	PST_SELECT_USER_ID					= 30,
//	PST_WAIT_USER_APP_SMS_AUTH			= 31,
//	PST_RECV_RIDER_PHOTO_USER_APP		= 32,
//	PST_RECV_FPROCESS_PHOTO				= 33,
//	PST_DOWNLOAD_FPROCESS_PHOTO			= 33,
//	PST_SEND_FCM						= 34,
//	PST_CHANGE_FORDER_STATE				= 35,
//	PST_BOARDING_RIDER_PHOTO			= 36,
//	PST_LOGI_HELP_AGREE_TEXT			= 37,
//	PST_FPROCESS_STORE_APP_INFO			= 38,
//	PST_INTER_FPROCESS_DATA				= 39,
//	PST_SEND_FCM_FOR_BANAPLES			= 40,
//	PST_SHUTTLE_REPORT					= 41,
//	PST_SHUTTLE_BASIC_INFO				= 42,
//	PST_MAKE_FPROCESS_HAPPY_CALL		= 43,
//	PST_FPROCESS_DISPLAY_PAGE_STATUS	= 44,
//	PST_UPLOAD_FPROCESS_PHOTO			= 45,
//	PST_DOWNLOAD_ZIBSURI_PHOTO			= 46,
//	PST_UPLOAD_ZIBSURI_PHOTO			= 47,
//	PST_SCAN_FPROCESS_BARCODE			= 48,
//	PST_INTER_FPROCESS_DATA_SINGLE		= 49,	
//	PST_INTER_FPROCESS_DATA_NEW			= 50,	//PST_INTER_FPROCESS_DATA와 비슷한데, FCODESUB 기준으로 데이터 대량 전송
//	PST_SEND_SMS_AUTH_FOR_LOGIN2		= 51,
//	PST_POINT_LOCATION_INFO2			= 52,
//
//};
//
////HelpApp의 서버의 쿼리 결과를 다른 HelpApp으로 넘겨줄 때 사용하는 프로토콜
//enum SUB_PROTOCOL_HELP_APP_SERVER
//{
//	PST_FROM_HELP_APP_SERVER		= 200,
//	PST_SHUTTLE_BOARDING_COUNT		= 201,
//	PST_GET_MIC_CONTROL_RESULT		= 202,
//	PST_VOICE_DATA_FROM_SERVER		= 203,
//	PST_SHUTTLE_BOARDING_STATE		= 204
//};
//
//
//enum SUB_PROTOCOL_SERVER_MSG
//{
//	PST_SERVER_MSG_ALLOC		= 200,
//	PST_SERVER_MSG_RF_CARD		= 201,
//	PST_SERVER_MSG_RIDER_POS	= 202,
//	PST_SERVER_MSG_WORK_REPORT	= 203,
//	PST_SERVER_MSG_AA_ALLOC		= 204,
//	PST_SERVER_MSG_SHUTTLE_POS	= 205
//};
//
//enum SERVER_NOTICE
//{
//	NOTICE_DUPLICATE_LOGIN			= 0,
//	NOTICE_DONT_SEND_ORDER			= 1,
//	NOTICE_WORK_STOP_FROM_OFFICE	= 2,
//	NOTICE_NEED_WORK_REPORT			= 3,
//	NOTICE_ALLOCATE_LOCK_TIME		= 4,
//	NOTICE_ORDER_NOTICE				= 5
//};
//
//
//
//enum PST_INTER_FPROCESS
//{ 
//	FPROCESS_CHANGE_FORDER_STATE			= 1,
//	FPROCESS_PRINT_LABEL					= 2, 
//	FPROCESS_PRESS_CALL_BELL				= 3,
//	FPROCESS_SCAN_BARCORD					= 4,
//	FPROCESS_DUTCH_MACHINE_STATE			= 5,
//	FPROCESS_TELSERVER_CALL_INFO			= 10,
//	FPROCESS_KIOSK_CASH						= 11,
//	FPROCESS_KIOSK_CASH_RECEIPT_ERROR		= 12,
//	FPROCESS_CARD_NICE_VAN					= 13,
//	FPROCESS_POSSPASS_RESTART				= 14,
//	FPROCESS_ORDER_LABEL					= 15,
//	FPROCESS_LABEL_FREE_GIFT				= 16,
//	FPROCESS_CASH_RECEIPT					= 17,
//	FPROCESS_EVENT_LABEL					= 18,
//	FPROCESS_DELETE_ORDER					= 19,
//	FPROCESS_CARD_CANCEL_MUIN				= 20,
//	FPROCESS_CHANGE_SETTING					= 21,
//	FPROCESS_LED_ON							= 22,
//	FPROCESS_LED_CHANGE_SETTING				= 23,
//	FPROCESS_CHECK_KIOSK					= 24,
//	FPROCESS_UPDATE_ORDER_STATE_KIOSK		= 25,
//	FPROCESS_CHECK_FROM_KIOSK				= 26,
//	FPROCESS_DOLL_ON						= 27,
//	FPROCESS_LABEL_PRINTER_STATE			= 28
//
//};
//
//enum INTER_FPROCESS_TARGET
//{
//	FPROCESS_STORE_APP_ONLY		=	0x01,       //"FProcessF"
//	FPROCESS_RING_APP_ONLY		=	0x02,		//"FProcessF_WATCH", "FProcessF_PHONE"
//	FPROCESS_ALL_APP			=   0x0F
//};




//서버용은 def.h 파일에 메모리풀을 이용하여, CStatInfo로 정의되어 있다.
#ifndef _MKSERVER

#pragma warning(disable: 4200)

typedef struct {
	UINT nReadBps;
	UINT nSendBps;
	UINT nConnection;
	UINT nCurQuery;
	UINT nTotalQuery;
	UINT nSessionFail;
	UINT nTransFail;

	UINT nRefreshCount;
	UINT nAllocateCount;
	UINT nCompleteCount;
	UINT nFailLoginCount;
	UINT nRestrictConnCount;
	char szVersion[20];

	UINT nActiveThread;
	UINT nProgramMemory;
	UINT nCpuUsage;
	double fMemUsage;
	COleDateTime dtStart;
	UINT nMaxThreadCount;
	UINT nSOThread;
	UINT nRFU2;
	UINT nRFU3;
	DWORD dwErrorTickCount;
	char szErrorLog[0];
} STATSTRUCT, *PSTATSTRUCT;


#endif




