#pragma once


// CAutoGenerateDlg 대화 상자입니다.

class CAutoGenerateDlg : public CMyDialog
{
	DECLARE_DYNAMIC(CAutoGenerateDlg)

public:
	CAutoGenerateDlg(CWnd* pParent = NULL);   // 표준 생성자입니다.
	virtual ~CAutoGenerateDlg();

// 대화 상자 데이터입니다.
	enum { IDD = IDD_AUTO_GENERATE_DLG };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV 지원입니다.

	DECLARE_MESSAGE_MAP()
public:
	afx_msg void OnBnClickedOk();


public:
	CString m_strFrom;
	CString m_strTo;
	CString m_strUnit;
	CString m_strDeposit;
};
